using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventApplication.Models
{
    public class SampleData : DropCreateDatabaseAlways<EventApplicationDB>
    {
        protected override void Seed(EventApplicationDB context)
        {
            var eventTypes = new List<EventType>
            {
                new EventType{ Title = "Class" },
                new EventType{ Title = "Concert" },
                new EventType{ Title = "Conference" },
                new EventType{ Title = "Convention" },
                new EventType{ Title = "Exposition" },
                new EventType{ Title = "Festival" },
                new EventType{ Title = "Party" },
                new EventType{ Title = "Race" },
                new EventType{ Title = "Tri-Athlon" },
                new EventType{ Title = "Workshop" },
            };

            new List<Event>
            {
                
                
                new Event { Type = eventTypes.Single(e => e.Title == "Exposition"), Title = "Example Expo 2", Desc = "This is a sample Desc for Example Expo 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(7).ToString()), City = "Austin", State = "Texas", OrgName = "Sam Ranooda", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Exposition"), Title = "Example Expo 3", Desc = "This is a sample Desc for Example Expo 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Parma", State = "Ohio", OrgName = "Tyler Yefet", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 1", Desc = "This is a sample Desc for Example Festival 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(-4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Parma", State = "Ohio", OrgName = "Micheal Cook", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Past event 1
                new Event { Type = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 2", Desc = "This is a sample Desc for Example Festival 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), City = "Cleveland", State = "Ohio", OrgName = "Arturo Kelly", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 3", Desc = "This is a sample Desc for Example Festival 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Austin", State = "Texas", OrgName = "Sean Kelly", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 1", Desc = "This is a sample Desc for Example Party 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(15).ToString()), City = "Cleveland", State = "Ohio", OrgName = "Mich Flenderson", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 1", Desc = "This is a sample Desc for Example Convention 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(19).ToString()), City = "Las Vegas", State = "Nevada", OrgName = "Lauren Matice", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 2", Desc = "This is a sample Desc for Example Convention 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(16).ToString()), City = "Columbus", State = "Ohio", OrgName = "Shirley T. Coons", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 2", Desc = "This is a sample Desc for Example Class 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(-9).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-6).ToString()), City = "Miami", State = "Florida", OrgName = "Janet Doun", OrgContact = "123-456-7890", TicMax = 75, TicAvail = 75 }, // Past event 2
                new Event { Type = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 3", Desc = "This is a sample Desc for Example Class 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Jacksonville", State = "Florida", OrgName = "Kris Daniels", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Last minute deal 1
                new Event { Type = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 1", Desc = "This is a sample Desc for Example Concert 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), City = "Strongsville", State = "Ohio", OrgName = "Brandon Ramirez", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 2", Desc = "This is a sample Desc for Example Concert 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(-5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Las Vegas", State = "Nevada", OrgName = "Sammy McCorrmic", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Past event 3
                new Event { Type = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 3", Desc = "This is a sample Desc for Example Concert 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Tampa", State = "Florida", OrgName = "Edward Timally", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Last minute deal 2
                new Event { Type = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 1", Desc = "This is a sample Desc for Example Conference 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(10).ToString()), City = "Orlando", State = "Florida", OrgName = "Sara Rinoda", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 2", Desc = "This is a sample Desc for Example Conference 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Laredo", State = "Texas", OrgName = "William Gorrey", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 3", Desc = "This is a sample Desc for Example Conference 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Parma", State = "Ohio", OrgName = "Kyle Plans", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Last minute deal 3
                new Event { Type = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 1", Desc = "This is a sample Desc for Example Class 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(7).ToString()), City = "Dallas", State = "Texas", OrgName = "Vincent Tommas", OrgContact = "123-456-7890", TicMax = 50, TicAvail = 27 },
				new Event { Type = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 3", Desc = "This is a sample Desc for Example Convention 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(17).ToString()), City = "Laredo", State = "Texas", OrgName = "Abby Corric", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Exposition"), Title = "Example Expo 1", Desc = "This is a sample Desc for Example Expo 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(14).ToString()), City = "Cincinnati", State = "Ohio", OrgName = "Moses Isreal", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 1", Desc = "This is a sample Desc for Example Race 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Akron", State = "Ohio", OrgName = "Micheal Kelly", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 3", Desc = "This is a sample Desc for Example Workshop 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(7).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(15).ToString()), City = "Cincinnati", State = "Ohio", OrgName = "Monica Geller", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
				new Event { Type = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 2", Desc = "This is a sample Desc for Example Race 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(-5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Parma", State = "Ohio", OrgName = "Mary Becka", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Past event 4
                new Event { Type = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 3", Desc = "This is a sample Desc for Example Race 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(18).ToString()), City = "Tampa", State = "Florida", OrgName = "Ronald McDonald", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Tri-Athlon"), Title = "Example Tri-Athlon 1", Desc = "This is a sample Desc for Example Tri-Athlon 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(16).ToString()), City = "Akron", State = "Ohio", OrgName = "John Calhoon", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Tri-Athlon"), Title = "Example Tri-Athlon 2", Desc = "This is a sample Desc for Example Tri-Athlon 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(13).ToString()), City = "Las Vegas", State = "Nevada", OrgName = "Denise Dander", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Tri-Athlon"), Title = "Example Tri-Athlon 3", Desc = "This is a sample Desc for Example Tri-Athlon 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(-9).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-1).ToString()), City = "Cincinnati", State = "Ohio", OrgName = "Debbie Little", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Past event 5
                new Event { Type = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 1", Desc = "This is a sample Desc for Example Workshop 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(15).ToString()), City = "Parma", State = "Ohio", OrgName = "Timmy D. Sinner", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
                new Event { Type = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 2", Desc = "This is a sample Desc for Example Workshop 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), City = "Columbus", State = "Ohio", OrgName = "Sean Minnet", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Last minute deal 4
               new Event { Type = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 2", Desc = "This is a sample Desc for Example Party 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(14).ToString()), City = "Houston", State = "Texas", OrgName = "John Zeigler", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 }, // Last minute deal 5
                new Event { Type = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 3", Desc = "This is a sample Desc for Example Party 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Laredo", State = "Texas", OrgName = "Robert Kelly", OrgContact = "123-456-7890", TicMax = 100, TicAvail = 100 },
			}.ForEach(e => context.Events.Add(e));

            context.Configuration.ValidateOnSaveEnabled = false;
            context.SaveChanges();
        }
    }
}